# This is where the strings go, that are written by
# Write-PSFMessage, Stop-PSFFunction or the PSFramework validation scriptblocks
@{
	'APICall.Add-FMAddress'                 = '#{0}: Adding {1} addresses to ADOM {2}'
	'APICall.Add-FMFirewallService'         = '#{0}: Adding {1} firewall services to ADOM {2}'
	'APICall.Add-FMAddressGroup'            = '#{0}: Adding {1} address groups to ADOM {2}'
	'APICall.Add-FMFirewallPolicy'          = '#{0}: Adding {1} policies in ADOM {2}, Policy Package {3}'
	'APICall.Add-FMInterface'               = '#{0}: Adding {1} interfaces to ADOM {2}'
	'APICall.Connect-FM'                    = '#{0}: Connecting to Fortigate instance {1} with user {2}'
	'APICall.Disconnect-FM'                 = '#{0}: Disconnecting Session'
	'APICall.Get-FMAddress'                 = '#{0}: Query addresses, {1} parameters used'
	'APICall.Get-FMAddressGroup'            = '#{0}: Query address groups, {1} parameters used'
	'APICall.Get-FMAdomLockStatus'          = '#{0}: Query current Lockstatus of ADOM {1}'
	'APICall.Get-FMDeviceInfo'              = '#{0}: Query device Info of ADOM {1}'
	'APICall.Get-FMFirewallPolicy'          = '#{0}: Query Firewall-Policy from ADOM {1}/Policy Package {2}'
	'APICall.Get-FMFirewallService'         = '#{0}: Query Firewall-Services from ADOM {1}'
	'APICall.Get-FMFirewallHitCount'        = '#{0}: Query Hitcount for ADOM {1} & Package {2}'
	'APICall.Get-FMInterface'               = '#{0}: Query Interfaces for ADOM {1}'
	'APICall.Get-FMPolicyPackage'           = '#{0}: Query Policy Packages'
	'APICall.Get-FMSystemStatus'            = '#{0}: Query Systemstatus'
	'APICall.Get-FMTaskResult'              = '#{0}: Query results of task {1}'
	'APICall.Get-FMTaskStatus'              = '#{0}: Query Status of task {1}'
	'APICall.Lock-FMAdom'                   = '#{0}: Locking ADOM {1}'
	'APICall.Move-FMFirewallPolicy'         = '#{0}: Moving Policy {1} {2} {3}, ADOM {4}/Policy Package {5}'
	'APICall.Publish-FMAdomChange'          = '#{0}: Saving changes'
	'APICall.Remove-FMAddress'              = '#{0}: Remove address {1}'
	'APICall.Remove-FMAddressGroup'         = '#{0}: Remove address group {1}'
	'APICall.Remove-FMFirewallPolicy'       = '#{0}: Remove firewall policy {1}'
	'APICall.Remove-FMFirewallPolicy.Multi' = '#{0}: Removing {1} firewall policy rules'
	'APICall.Remove-FMInterface'            = '#{0}: Remove interface {1}'
	'APICall.Rename-FMAddress'              = '#{0}: Renaming {1} addresses in ADOM {2}'
	'APICall.Rename-FMAddressGroup'         = '#{0}: Renaming {1} addressgroups in ADOM {2}'
	'APICall.Rename-FMInterface'            = '#{0}: Renaming {1} interfaces in ADOM {2}'
	'APICall.Unlock-FMAdom'                 = '#{0}: Unlocking ADOM {1}'
	'APICall.Update-FMAddress'              = '#{0}: Updating {1} addresses in ADOM {2}, additional -Name: {3}'
	'APICall.Update-FMAddressGroup'         = '#{0}: Updating {1} addressgroups in ADOM {2}, additional -Name: {3}'
	'APICall.Update-FMFirewallPolicy'       = '#{0}: Updating {1} policies in ADOM {2}, Policy Package {3}'
	'APICall.Update-FMFirewallService'      = '#{0}: Updating {1} firewall services in ADOM {2}, additional -Name: {3}'
	'APICall.Update-FMInterface'            = '#{0}: Updating {1} interfaces in ADOM {2}, additional -Name: {3}'
	'Connect-FM.Connected'                  = '#{0}: Connection established' #
	'Connect-FM.NotConnected'               = '#{0}: Connection could not be established'
}